# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci(n)
	fibs = []
	n1 = 0
	n2 = 1 
	while n1 < n
		fibs << n1 if n1.even?
		n1,n2 = n2, n1+n2
	end
	fibs.inject(:+)
end

puts fibonacci(4000000)